### ISSUE TITLE
Thank you for the fantastic software! I would like to set the thread parameter for FFmpeg. Could you please guide me on how to do this?

### ISSUE THREAD

**Issue by sainiudit** [BrokenSource/DepthFlow#42]
### 🔘 Request type

General feedback

### 🔘 Description

Thank you for the fantastic software! I would like to set the thread parameter for FFmpeg. Could you please guide me on how to do this?

**Comment by Tremeschin** [comment]
Good catch, I should make these general settings available on the CLI, but it's possible to set it directly on a scene's ffmpeg class, you can do it with:

```python
from DepthFlow import DepthScene

if __name__ == "__main__":
    scene = DepthScene()
    scene.ffmpeg.threads = 2
    scene.main(output="./video.mp4")
```

I'm almost sure this won't work on current release v0.6.0 in [PyPI](https://pypi.org/project/depthflow/), as it was a recent change on [git main](https://github.com/BrokenSource/ShaderFlow/commit/5aa6b4a288c3e38907ed462b1068034eeb2ec60f#diff-00377b1f67bd85923fa2febc0605f35dc920c2cdca7ff761fee289454ab25305L743) only, so either run [from source](https://brokensrc.dev/get/source/) or wait for a v0.7 :)

**Comment by sainiudit** [comment]
@Tremeschin  Thanks for the immediate response but using setting threads directly giving error
'NoneType' object has no attribute 'threads'

![image](https://github.com/user-attachments/assets/e564947b-e517-4176-910c-2c1e6b62d49d)

**Comment by Tremeschin** [comment]
I'm assuming you're running from a pip install, adding to my last comment this v0.6 had the FFmpeg class recreated every time on the scene's main, so it wasn't configurable like the example I provided and how it can work now on git main

You can for the moment install the latest versions of everything, will need a:

- `pip install git+https://github.com/BrokenSource/BrokenSource.git`
- `pip install git+https://github.com/BrokenSource/ShaderFlow.git`
- `pip install git+https://github.com/BrokenSource/DepthFlow.git`

and the last comment's example should work then

**Comment by Tremeschin** [comment]
**Sidenote:** I see that the opengl rendered is llvmpipe, you're likely running inside a docker container locally or on the cloud

Problem is, llvmpipe is cpu rendering, _and speeds will be as bad as 2 frames per second up to 12 seconds per frame!_

I have a write-up on properly checking/setting up docker stuff here https://brokensrc.dev/get/docker/ , but if it's a cloud provider, just saying in advance that the only one me + a couple of users managed to get gpu accelerationg working was modal dot com _(not sponsored)_, and only after asking their support team to enable it

I have a [docker-compose.yml](https://github.com/BrokenSource/BrokenSource/blob/main/docker-compose.yml) in the main repo and other [dockerfiles](https://github.com/BrokenSource/BrokenSource/tree/main/Docker) as well for reference, that should work locally

**Comment by sainiudit** [comment]
Yes I am running it on cloud and it is slow 2 -6 second per frame.
Thanks it worked after installing from source.

**Comment by Tremeschin** [comment]
Awesome! I'll close as it'll be possible on the v0.7 soon and it was a very specific request 👍🏻

I'll be pushing a couple commits to main and it might break stuff, but you can pin those pip install git+ versions to the current commit that worked with:

- `pip install git+https://github.com/BrokenSource/BrokenSource.git@85e172b`
- `pip install git+https://github.com/BrokenSource/ShaderFlow.git@0d4411b`
- `pip install git+https://github.com/BrokenSource/DepthFlow.git@fc7d421`

feel free to open new issues or continue the talk here! :)

**Comment by Tremeschin** [comment]
A, backtracking a bit, the 0.7 was released and the provided example should work as a feature now!
